site_name: sknnr
repo_url: https://github.com/lemma-osu/sknnr
repo_name: lemma-osu/sknnr
docs_dir: pages/

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - "API Reference":
    - Estimators:
      - RawKNNRegressor: api/estimators/raw.md
      - EuclideanKNNRegressor: api/estimators/euclidean.md
      - MahalanobisKNNRegressor: api/estimators/mahalanobis.md
      - GNNRegressor: api/estimators/gnn.md
      - MSNRegressor: api/estimators/msn.md
    - Transformers:
      - StandardScalerWithDOF: api/transformers/standardscalerwithdof.md
      - MahalanobisTransformer: api/transformers/mahalanobis.md
      - CCATransformer: api/transformers/cca.md
      - CCorATransformer: api/transformers/ccora.md
    - Datasets:
      - Dataset: api/datasets/dataset.md
      - "Moscow Mountain / St. Joes": api/datasets/moscow_stjoes.md
      - "SWO Ecoplot": api/datasets/swo_ecoplot.md
  - Contributing: contributing.md

theme: 
  name: material
  features: 
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.path
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_source: false
            inherited_members: true
            undoc_members: true
            docstring_style: numpy
            show_if_no_docstring: true
            show_signature_annotations: true
            show_root_heading: true
            show_category_heading: true
            merge_init_into_class: true
            signature_crossrefs: true

markdown_extensions:
  - abbr
  - admonition
  - tables
  - footnotes
  - toc:
      permalink: true
  - pymdownx.snippets:
      auto_append:
        - docs/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
